version: '3.1'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      # Use postgres/example user/password credentials
      POSTGRES_PASSWORD: example

  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - 5050:5050

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example