version: '3.1'

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      # Use postgres/example user/password credentials
      POSTGRES_PASSWORD: example

  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - 5050:5050