version: '3.1'

services:

  app:
    image: erlang:20
    volumes:
      ".:/opt/reconnections"
    command: erl -pa /_build/default/lib/*/ebin/ -config /conf/sys

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      # Use postgres/example user/password credentials
      POSTGRES_PASSWORD: example

  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - 5050:5050

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
